language: cpp
sudo: false

os: linux

git:
  depth: 1

matrix:
  include:
      # g++ 7 on Linux with C++17
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=17
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - env: COMPILER=g++-6 BUILD=Release STANDARD=17
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      # Apple clang on OS X with C++17
    - env: BUILD=Debug STANDARD=17
      compiler: clang
      os: osx
    - env: BUILD=Release STANDARD=17
      compiler: clang
      os: osx
      # clang 6.0 on Linux with C++17
    - env: COMPILER=clang++-6.0 BUILD=Debug STANDARD=17
      compiler: clang
      addons:
        apt:
          update: true
          packages:
            - clang-6.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-trusty-6.0
  allow_failures:
      # Errors
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=17
      compiler: gcc

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CXX=${COMPILER}; fi

script:
  - mkdir -p yop2p_build
  - cd yop2p_build
  - cmake ../ $TRAVIS_BUILD_DIR
  - make


