language: cpp
dist: bionic
sudo: false

os: linux

git:
  depth: 1

matrix:
  include:
      # Documentation
    - env: BUILD=Doc
      sudo: required
      # g++ 7 on Linux with C++17
    - env: COMPILER=g++-7 BUILD=Debug STANDARD=17
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - env: COMPILER=g++-7 BUILD=Release STANDARD=17
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      # Apple clang on OS X with C++17
    - env: BUILD=Debug STANDARD=17
      compiler: clang
      os: osx
    - env: BUILD=Release STANDARD=17
      compiler: clang
      os: osx
      # clang 6.0 on Linux with C++17
    - env: COMPILER=clang++-6.0 BUILD=Debug STANDARD=17
      compiler: clang
      addons:
        apt:
          update: true
          packages:
            - clang-6.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic
            - llvm-toolchain-bionic-6.0
  allow_failures:
      # Errors
    - env: COMPILER=g++-7 BUILD=Debug STANDARD=17
      compiler: gcc

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CXX=${COMPILER}; fi
  - if [[ "${BUILD}" != "Doc" ]]; then ${CXX} --version; fi

script:
  - support/travis-build.py
